// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Hello_cpp
void Hello_cpp();
RcppExport SEXP _MPIHelloWorld_Hello_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Hello_cpp();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MPIHelloWorld_Hello_cpp", (DL_FUNC) &_MPIHelloWorld_Hello_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MPIHelloWorld(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
